version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=production
#      - DATABASE_URL=postgresql://startup_user:startup_password@db:5432/startup_weekend?ssldisabled=1
#      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
#      - NEXTAUTH_URL=${NEXTAUTH_URL}
#      - SMTP_HOST=${SMTP_HOST}
#      - SMTP_PORT=${SMTP_PORT}
#      - SMTP_USER=${SMTP_USER}
#      - SMTP_PASS=${SMTP_PASS}
#      - ADMIN_NAME=${ADMIN_NAME}
#      - ADMIN_EMAIL=${ADMIN_EMAIL}
#      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
#    depends_on:
#      - db
#    volumes:
#      - uploads:/app/uploads

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: startup_user
      POSTGRES_PASSWORD: startup_password
      POSTGRES_DB: startup_weekend
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  uploads: